/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package se.lth.cs.docforia.io.thrift;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import javax.annotation.Generated;
import java.nio.ByteBuffer;
import java.util.*;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-11-03")
public class TColumn implements org.apache.thrift.TBase<TColumn, TColumn._Fields>, java.io.Serializable, Cloneable, Comparable<TColumn> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TColumn");

  private static final org.apache.thrift.protocol.TField BINARY_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("binaryValues", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField STRING_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("stringValues", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField BOOL_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("boolValues", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField INT_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("intValues", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField LONG_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("longValues", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField DOUBLE_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("doubleValues", org.apache.thrift.protocol.TType.LIST, (short)7);
  private static final org.apache.thrift.protocol.TField DOC_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("docValues", org.apache.thrift.protocol.TType.LIST, (short)8);
  private static final org.apache.thrift.protocol.TField PROPMAP_VALUES_FIELD_DESC = new org.apache.thrift.protocol.TField("propmapValues", org.apache.thrift.protocol.TType.LIST, (short)9);
  private static final org.apache.thrift.protocol.TField LENGTH_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("lengthInfo", org.apache.thrift.protocol.TType.LIST, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TColumnStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TColumnTupleSchemeFactory());
  }

  public List<ByteBuffer> binaryValues; // required
  public List<String> stringValues; // required
  public List<Boolean> boolValues; // required
  public List<Integer> intValues; // required
  public List<Long> longValues; // required
  public List<Double> doubleValues; // required
  public List<TDocument> docValues; // required
  public List<TPropertyMap> propmapValues; // required
  public List<Integer> lengthInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BINARY_VALUES((short)1, "binaryValues"),
    STRING_VALUES((short)2, "stringValues"),
    BOOL_VALUES((short)3, "boolValues"),
    INT_VALUES((short)4, "intValues"),
    LONG_VALUES((short)5, "longValues"),
    DOUBLE_VALUES((short)7, "doubleValues"),
    DOC_VALUES((short)8, "docValues"),
    PROPMAP_VALUES((short)9, "propmapValues"),
    LENGTH_INFO((short)10, "lengthInfo");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BINARY_VALUES
          return BINARY_VALUES;
        case 2: // STRING_VALUES
          return STRING_VALUES;
        case 3: // BOOL_VALUES
          return BOOL_VALUES;
        case 4: // INT_VALUES
          return INT_VALUES;
        case 5: // LONG_VALUES
          return LONG_VALUES;
        case 7: // DOUBLE_VALUES
          return DOUBLE_VALUES;
        case 8: // DOC_VALUES
          return DOC_VALUES;
        case 9: // PROPMAP_VALUES
          return PROPMAP_VALUES;
        case 10: // LENGTH_INFO
          return LENGTH_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BINARY_VALUES, new org.apache.thrift.meta_data.FieldMetaData("binaryValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING            , true))));
    tmpMap.put(_Fields.STRING_VALUES, new org.apache.thrift.meta_data.FieldMetaData("stringValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.BOOL_VALUES, new org.apache.thrift.meta_data.FieldMetaData("boolValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL))));
    tmpMap.put(_Fields.INT_VALUES, new org.apache.thrift.meta_data.FieldMetaData("intValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.LONG_VALUES, new org.apache.thrift.meta_data.FieldMetaData("longValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.DOUBLE_VALUES, new org.apache.thrift.meta_data.FieldMetaData("doubleValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    tmpMap.put(_Fields.DOC_VALUES, new org.apache.thrift.meta_data.FieldMetaData("docValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "TDocument"))));
    tmpMap.put(_Fields.PROPMAP_VALUES, new org.apache.thrift.meta_data.FieldMetaData("propmapValues", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TPropertyMap.class))));
    tmpMap.put(_Fields.LENGTH_INFO, new org.apache.thrift.meta_data.FieldMetaData("lengthInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TColumn.class, metaDataMap);
  }

  public TColumn() {
  }

  public TColumn(
    List<ByteBuffer> binaryValues,
    List<String> stringValues,
    List<Boolean> boolValues,
    List<Integer> intValues,
    List<Long> longValues,
    List<Double> doubleValues,
    List<TDocument> docValues,
    List<TPropertyMap> propmapValues,
    List<Integer> lengthInfo)
  {
    this();
    this.binaryValues = binaryValues;
    this.stringValues = stringValues;
    this.boolValues = boolValues;
    this.intValues = intValues;
    this.longValues = longValues;
    this.doubleValues = doubleValues;
    this.docValues = docValues;
    this.propmapValues = propmapValues;
    this.lengthInfo = lengthInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TColumn(TColumn other) {
    if (other.isSetBinaryValues()) {
      List<ByteBuffer> __this__binaryValues = new ArrayList<ByteBuffer>(other.binaryValues);
      this.binaryValues = __this__binaryValues;
    }
    if (other.isSetStringValues()) {
      List<String> __this__stringValues = new ArrayList<String>(other.stringValues);
      this.stringValues = __this__stringValues;
    }
    if (other.isSetBoolValues()) {
      List<Boolean> __this__boolValues = new ArrayList<Boolean>(other.boolValues);
      this.boolValues = __this__boolValues;
    }
    if (other.isSetIntValues()) {
      List<Integer> __this__intValues = new ArrayList<Integer>(other.intValues);
      this.intValues = __this__intValues;
    }
    if (other.isSetLongValues()) {
      List<Long> __this__longValues = new ArrayList<Long>(other.longValues);
      this.longValues = __this__longValues;
    }
    if (other.isSetDoubleValues()) {
      List<Double> __this__doubleValues = new ArrayList<Double>(other.doubleValues);
      this.doubleValues = __this__doubleValues;
    }
    if (other.isSetDocValues()) {
      List<TDocument> __this__docValues = new ArrayList<TDocument>(other.docValues.size());
      for (TDocument other_element : other.docValues) {
        __this__docValues.add(other_element);
      }
      this.docValues = __this__docValues;
    }
    if (other.isSetPropmapValues()) {
      List<TPropertyMap> __this__propmapValues = new ArrayList<TPropertyMap>(other.propmapValues.size());
      for (TPropertyMap other_element : other.propmapValues) {
        __this__propmapValues.add(new TPropertyMap(other_element));
      }
      this.propmapValues = __this__propmapValues;
    }
    if (other.isSetLengthInfo()) {
      List<Integer> __this__lengthInfo = new ArrayList<Integer>(other.lengthInfo);
      this.lengthInfo = __this__lengthInfo;
    }
  }

  public TColumn deepCopy() {
    return new TColumn(this);
  }

  @Override
  public void clear() {
    this.binaryValues = null;
    this.stringValues = null;
    this.boolValues = null;
    this.intValues = null;
    this.longValues = null;
    this.doubleValues = null;
    this.docValues = null;
    this.propmapValues = null;
    this.lengthInfo = null;
  }

  public int getBinaryValuesSize() {
    return (this.binaryValues == null) ? 0 : this.binaryValues.size();
  }

  public java.util.Iterator<ByteBuffer> getBinaryValuesIterator() {
    return (this.binaryValues == null) ? null : this.binaryValues.iterator();
  }

  public void addToBinaryValues(ByteBuffer elem) {
    if (this.binaryValues == null) {
      this.binaryValues = new ArrayList<ByteBuffer>();
    }
    this.binaryValues.add(elem);
  }

  public List<ByteBuffer> getBinaryValues() {
    return this.binaryValues;
  }

  public TColumn setBinaryValues(List<ByteBuffer> binaryValues) {
    this.binaryValues = binaryValues;
    return this;
  }

  public void unsetBinaryValues() {
    this.binaryValues = null;
  }

  /** Returns true if field binaryValues is set (has been assigned a value) and false otherwise */
  public boolean isSetBinaryValues() {
    return this.binaryValues != null;
  }

  public void setBinaryValuesIsSet(boolean value) {
    if (!value) {
      this.binaryValues = null;
    }
  }

  public int getStringValuesSize() {
    return (this.stringValues == null) ? 0 : this.stringValues.size();
  }

  public java.util.Iterator<String> getStringValuesIterator() {
    return (this.stringValues == null) ? null : this.stringValues.iterator();
  }

  public void addToStringValues(String elem) {
    if (this.stringValues == null) {
      this.stringValues = new ArrayList<String>();
    }
    this.stringValues.add(elem);
  }

  public List<String> getStringValues() {
    return this.stringValues;
  }

  public TColumn setStringValues(List<String> stringValues) {
    this.stringValues = stringValues;
    return this;
  }

  public void unsetStringValues() {
    this.stringValues = null;
  }

  /** Returns true if field stringValues is set (has been assigned a value) and false otherwise */
  public boolean isSetStringValues() {
    return this.stringValues != null;
  }

  public void setStringValuesIsSet(boolean value) {
    if (!value) {
      this.stringValues = null;
    }
  }

  public int getBoolValuesSize() {
    return (this.boolValues == null) ? 0 : this.boolValues.size();
  }

  public java.util.Iterator<Boolean> getBoolValuesIterator() {
    return (this.boolValues == null) ? null : this.boolValues.iterator();
  }

  public void addToBoolValues(boolean elem) {
    if (this.boolValues == null) {
      this.boolValues = new ArrayList<Boolean>();
    }
    this.boolValues.add(elem);
  }

  public List<Boolean> getBoolValues() {
    return this.boolValues;
  }

  public TColumn setBoolValues(List<Boolean> boolValues) {
    this.boolValues = boolValues;
    return this;
  }

  public void unsetBoolValues() {
    this.boolValues = null;
  }

  /** Returns true if field boolValues is set (has been assigned a value) and false otherwise */
  public boolean isSetBoolValues() {
    return this.boolValues != null;
  }

  public void setBoolValuesIsSet(boolean value) {
    if (!value) {
      this.boolValues = null;
    }
  }

  public int getIntValuesSize() {
    return (this.intValues == null) ? 0 : this.intValues.size();
  }

  public java.util.Iterator<Integer> getIntValuesIterator() {
    return (this.intValues == null) ? null : this.intValues.iterator();
  }

  public void addToIntValues(int elem) {
    if (this.intValues == null) {
      this.intValues = new ArrayList<Integer>();
    }
    this.intValues.add(elem);
  }

  public List<Integer> getIntValues() {
    return this.intValues;
  }

  public TColumn setIntValues(List<Integer> intValues) {
    this.intValues = intValues;
    return this;
  }

  public void unsetIntValues() {
    this.intValues = null;
  }

  /** Returns true if field intValues is set (has been assigned a value) and false otherwise */
  public boolean isSetIntValues() {
    return this.intValues != null;
  }

  public void setIntValuesIsSet(boolean value) {
    if (!value) {
      this.intValues = null;
    }
  }

  public int getLongValuesSize() {
    return (this.longValues == null) ? 0 : this.longValues.size();
  }

  public java.util.Iterator<Long> getLongValuesIterator() {
    return (this.longValues == null) ? null : this.longValues.iterator();
  }

  public void addToLongValues(long elem) {
    if (this.longValues == null) {
      this.longValues = new ArrayList<Long>();
    }
    this.longValues.add(elem);
  }

  public List<Long> getLongValues() {
    return this.longValues;
  }

  public TColumn setLongValues(List<Long> longValues) {
    this.longValues = longValues;
    return this;
  }

  public void unsetLongValues() {
    this.longValues = null;
  }

  /** Returns true if field longValues is set (has been assigned a value) and false otherwise */
  public boolean isSetLongValues() {
    return this.longValues != null;
  }

  public void setLongValuesIsSet(boolean value) {
    if (!value) {
      this.longValues = null;
    }
  }

  public int getDoubleValuesSize() {
    return (this.doubleValues == null) ? 0 : this.doubleValues.size();
  }

  public java.util.Iterator<Double> getDoubleValuesIterator() {
    return (this.doubleValues == null) ? null : this.doubleValues.iterator();
  }

  public void addToDoubleValues(double elem) {
    if (this.doubleValues == null) {
      this.doubleValues = new ArrayList<Double>();
    }
    this.doubleValues.add(elem);
  }

  public List<Double> getDoubleValues() {
    return this.doubleValues;
  }

  public TColumn setDoubleValues(List<Double> doubleValues) {
    this.doubleValues = doubleValues;
    return this;
  }

  public void unsetDoubleValues() {
    this.doubleValues = null;
  }

  /** Returns true if field doubleValues is set (has been assigned a value) and false otherwise */
  public boolean isSetDoubleValues() {
    return this.doubleValues != null;
  }

  public void setDoubleValuesIsSet(boolean value) {
    if (!value) {
      this.doubleValues = null;
    }
  }

  public int getDocValuesSize() {
    return (this.docValues == null) ? 0 : this.docValues.size();
  }

  public java.util.Iterator<TDocument> getDocValuesIterator() {
    return (this.docValues == null) ? null : this.docValues.iterator();
  }

  public void addToDocValues(TDocument elem) {
    if (this.docValues == null) {
      this.docValues = new ArrayList<TDocument>();
    }
    this.docValues.add(elem);
  }

  public List<TDocument> getDocValues() {
    return this.docValues;
  }

  public TColumn setDocValues(List<TDocument> docValues) {
    this.docValues = docValues;
    return this;
  }

  public void unsetDocValues() {
    this.docValues = null;
  }

  /** Returns true if field docValues is set (has been assigned a value) and false otherwise */
  public boolean isSetDocValues() {
    return this.docValues != null;
  }

  public void setDocValuesIsSet(boolean value) {
    if (!value) {
      this.docValues = null;
    }
  }

  public int getPropmapValuesSize() {
    return (this.propmapValues == null) ? 0 : this.propmapValues.size();
  }

  public java.util.Iterator<TPropertyMap> getPropmapValuesIterator() {
    return (this.propmapValues == null) ? null : this.propmapValues.iterator();
  }

  public void addToPropmapValues(TPropertyMap elem) {
    if (this.propmapValues == null) {
      this.propmapValues = new ArrayList<TPropertyMap>();
    }
    this.propmapValues.add(elem);
  }

  public List<TPropertyMap> getPropmapValues() {
    return this.propmapValues;
  }

  public TColumn setPropmapValues(List<TPropertyMap> propmapValues) {
    this.propmapValues = propmapValues;
    return this;
  }

  public void unsetPropmapValues() {
    this.propmapValues = null;
  }

  /** Returns true if field propmapValues is set (has been assigned a value) and false otherwise */
  public boolean isSetPropmapValues() {
    return this.propmapValues != null;
  }

  public void setPropmapValuesIsSet(boolean value) {
    if (!value) {
      this.propmapValues = null;
    }
  }

  public int getLengthInfoSize() {
    return (this.lengthInfo == null) ? 0 : this.lengthInfo.size();
  }

  public java.util.Iterator<Integer> getLengthInfoIterator() {
    return (this.lengthInfo == null) ? null : this.lengthInfo.iterator();
  }

  public void addToLengthInfo(int elem) {
    if (this.lengthInfo == null) {
      this.lengthInfo = new ArrayList<Integer>();
    }
    this.lengthInfo.add(elem);
  }

  public List<Integer> getLengthInfo() {
    return this.lengthInfo;
  }

  public TColumn setLengthInfo(List<Integer> lengthInfo) {
    this.lengthInfo = lengthInfo;
    return this;
  }

  public void unsetLengthInfo() {
    this.lengthInfo = null;
  }

  /** Returns true if field lengthInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetLengthInfo() {
    return this.lengthInfo != null;
  }

  public void setLengthInfoIsSet(boolean value) {
    if (!value) {
      this.lengthInfo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BINARY_VALUES:
      if (value == null) {
        unsetBinaryValues();
      } else {
        setBinaryValues((List<ByteBuffer>)value);
      }
      break;

    case STRING_VALUES:
      if (value == null) {
        unsetStringValues();
      } else {
        setStringValues((List<String>)value);
      }
      break;

    case BOOL_VALUES:
      if (value == null) {
        unsetBoolValues();
      } else {
        setBoolValues((List<Boolean>)value);
      }
      break;

    case INT_VALUES:
      if (value == null) {
        unsetIntValues();
      } else {
        setIntValues((List<Integer>)value);
      }
      break;

    case LONG_VALUES:
      if (value == null) {
        unsetLongValues();
      } else {
        setLongValues((List<Long>)value);
      }
      break;

    case DOUBLE_VALUES:
      if (value == null) {
        unsetDoubleValues();
      } else {
        setDoubleValues((List<Double>)value);
      }
      break;

    case DOC_VALUES:
      if (value == null) {
        unsetDocValues();
      } else {
        setDocValues((List<TDocument>)value);
      }
      break;

    case PROPMAP_VALUES:
      if (value == null) {
        unsetPropmapValues();
      } else {
        setPropmapValues((List<TPropertyMap>)value);
      }
      break;

    case LENGTH_INFO:
      if (value == null) {
        unsetLengthInfo();
      } else {
        setLengthInfo((List<Integer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BINARY_VALUES:
      return getBinaryValues();

    case STRING_VALUES:
      return getStringValues();

    case BOOL_VALUES:
      return getBoolValues();

    case INT_VALUES:
      return getIntValues();

    case LONG_VALUES:
      return getLongValues();

    case DOUBLE_VALUES:
      return getDoubleValues();

    case DOC_VALUES:
      return getDocValues();

    case PROPMAP_VALUES:
      return getPropmapValues();

    case LENGTH_INFO:
      return getLengthInfo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BINARY_VALUES:
      return isSetBinaryValues();
    case STRING_VALUES:
      return isSetStringValues();
    case BOOL_VALUES:
      return isSetBoolValues();
    case INT_VALUES:
      return isSetIntValues();
    case LONG_VALUES:
      return isSetLongValues();
    case DOUBLE_VALUES:
      return isSetDoubleValues();
    case DOC_VALUES:
      return isSetDocValues();
    case PROPMAP_VALUES:
      return isSetPropmapValues();
    case LENGTH_INFO:
      return isSetLengthInfo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TColumn)
      return this.equals((TColumn)that);
    return false;
  }

  public boolean equals(TColumn that) {
    if (that == null)
      return false;

    boolean this_present_binaryValues = true && this.isSetBinaryValues();
    boolean that_present_binaryValues = true && that.isSetBinaryValues();
    if (this_present_binaryValues || that_present_binaryValues) {
      if (!(this_present_binaryValues && that_present_binaryValues))
        return false;
      if (!this.binaryValues.equals(that.binaryValues))
        return false;
    }

    boolean this_present_stringValues = true && this.isSetStringValues();
    boolean that_present_stringValues = true && that.isSetStringValues();
    if (this_present_stringValues || that_present_stringValues) {
      if (!(this_present_stringValues && that_present_stringValues))
        return false;
      if (!this.stringValues.equals(that.stringValues))
        return false;
    }

    boolean this_present_boolValues = true && this.isSetBoolValues();
    boolean that_present_boolValues = true && that.isSetBoolValues();
    if (this_present_boolValues || that_present_boolValues) {
      if (!(this_present_boolValues && that_present_boolValues))
        return false;
      if (!this.boolValues.equals(that.boolValues))
        return false;
    }

    boolean this_present_intValues = true && this.isSetIntValues();
    boolean that_present_intValues = true && that.isSetIntValues();
    if (this_present_intValues || that_present_intValues) {
      if (!(this_present_intValues && that_present_intValues))
        return false;
      if (!this.intValues.equals(that.intValues))
        return false;
    }

    boolean this_present_longValues = true && this.isSetLongValues();
    boolean that_present_longValues = true && that.isSetLongValues();
    if (this_present_longValues || that_present_longValues) {
      if (!(this_present_longValues && that_present_longValues))
        return false;
      if (!this.longValues.equals(that.longValues))
        return false;
    }

    boolean this_present_doubleValues = true && this.isSetDoubleValues();
    boolean that_present_doubleValues = true && that.isSetDoubleValues();
    if (this_present_doubleValues || that_present_doubleValues) {
      if (!(this_present_doubleValues && that_present_doubleValues))
        return false;
      if (!this.doubleValues.equals(that.doubleValues))
        return false;
    }

    boolean this_present_docValues = true && this.isSetDocValues();
    boolean that_present_docValues = true && that.isSetDocValues();
    if (this_present_docValues || that_present_docValues) {
      if (!(this_present_docValues && that_present_docValues))
        return false;
      if (!this.docValues.equals(that.docValues))
        return false;
    }

    boolean this_present_propmapValues = true && this.isSetPropmapValues();
    boolean that_present_propmapValues = true && that.isSetPropmapValues();
    if (this_present_propmapValues || that_present_propmapValues) {
      if (!(this_present_propmapValues && that_present_propmapValues))
        return false;
      if (!this.propmapValues.equals(that.propmapValues))
        return false;
    }

    boolean this_present_lengthInfo = true && this.isSetLengthInfo();
    boolean that_present_lengthInfo = true && that.isSetLengthInfo();
    if (this_present_lengthInfo || that_present_lengthInfo) {
      if (!(this_present_lengthInfo && that_present_lengthInfo))
        return false;
      if (!this.lengthInfo.equals(that.lengthInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_binaryValues = true && (isSetBinaryValues());
    list.add(present_binaryValues);
    if (present_binaryValues)
      list.add(binaryValues);

    boolean present_stringValues = true && (isSetStringValues());
    list.add(present_stringValues);
    if (present_stringValues)
      list.add(stringValues);

    boolean present_boolValues = true && (isSetBoolValues());
    list.add(present_boolValues);
    if (present_boolValues)
      list.add(boolValues);

    boolean present_intValues = true && (isSetIntValues());
    list.add(present_intValues);
    if (present_intValues)
      list.add(intValues);

    boolean present_longValues = true && (isSetLongValues());
    list.add(present_longValues);
    if (present_longValues)
      list.add(longValues);

    boolean present_doubleValues = true && (isSetDoubleValues());
    list.add(present_doubleValues);
    if (present_doubleValues)
      list.add(doubleValues);

    boolean present_docValues = true && (isSetDocValues());
    list.add(present_docValues);
    if (present_docValues)
      list.add(docValues);

    boolean present_propmapValues = true && (isSetPropmapValues());
    list.add(present_propmapValues);
    if (present_propmapValues)
      list.add(propmapValues);

    boolean present_lengthInfo = true && (isSetLengthInfo());
    list.add(present_lengthInfo);
    if (present_lengthInfo)
      list.add(lengthInfo);

    return list.hashCode();
  }

  @Override
  public int compareTo(TColumn other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBinaryValues()).compareTo(other.isSetBinaryValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBinaryValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.binaryValues, other.binaryValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStringValues()).compareTo(other.isSetStringValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStringValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stringValues, other.stringValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBoolValues()).compareTo(other.isSetBoolValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBoolValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.boolValues, other.boolValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIntValues()).compareTo(other.isSetIntValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIntValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.intValues, other.intValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLongValues()).compareTo(other.isSetLongValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.longValues, other.longValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDoubleValues()).compareTo(other.isSetDoubleValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDoubleValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.doubleValues, other.doubleValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDocValues()).compareTo(other.isSetDocValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDocValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.docValues, other.docValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPropmapValues()).compareTo(other.isSetPropmapValues());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPropmapValues()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.propmapValues, other.propmapValues);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLengthInfo()).compareTo(other.isSetLengthInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLengthInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lengthInfo, other.lengthInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TColumn(");
    boolean first = true;

    sb.append("binaryValues:");
    if (this.binaryValues == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.binaryValues, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("stringValues:");
    if (this.stringValues == null) {
      sb.append("null");
    } else {
      sb.append(this.stringValues);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("boolValues:");
    if (this.boolValues == null) {
      sb.append("null");
    } else {
      sb.append(this.boolValues);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("intValues:");
    if (this.intValues == null) {
      sb.append("null");
    } else {
      sb.append(this.intValues);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("longValues:");
    if (this.longValues == null) {
      sb.append("null");
    } else {
      sb.append(this.longValues);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("doubleValues:");
    if (this.doubleValues == null) {
      sb.append("null");
    } else {
      sb.append(this.doubleValues);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("docValues:");
    if (this.docValues == null) {
      sb.append("null");
    } else {
      sb.append(this.docValues);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("propmapValues:");
    if (this.propmapValues == null) {
      sb.append("null");
    } else {
      sb.append(this.propmapValues);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("lengthInfo:");
    if (this.lengthInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.lengthInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TColumnStandardSchemeFactory implements SchemeFactory {
    public TColumnStandardScheme getScheme() {
      return new TColumnStandardScheme();
    }
  }

  private static class TColumnStandardScheme extends StandardScheme<TColumn> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TColumn struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BINARY_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list96 = iprot.readListBegin();
                struct.binaryValues = new ArrayList<ByteBuffer>(_list96.size);
                ByteBuffer _elem97;
                for (int _i98 = 0; _i98 < _list96.size; ++_i98)
                {
                  _elem97 = iprot.readBinary();
                  struct.binaryValues.add(_elem97);
                }
                iprot.readListEnd();
              }
              struct.setBinaryValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STRING_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list99 = iprot.readListBegin();
                struct.stringValues = new ArrayList<String>(_list99.size);
                String _elem100;
                for (int _i101 = 0; _i101 < _list99.size; ++_i101)
                {
                  _elem100 = iprot.readString();
                  struct.stringValues.add(_elem100);
                }
                iprot.readListEnd();
              }
              struct.setStringValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BOOL_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list102 = iprot.readListBegin();
                struct.boolValues = new ArrayList<Boolean>(_list102.size);
                boolean _elem103;
                for (int _i104 = 0; _i104 < _list102.size; ++_i104)
                {
                  _elem103 = iprot.readBool();
                  struct.boolValues.add(_elem103);
                }
                iprot.readListEnd();
              }
              struct.setBoolValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // INT_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list105 = iprot.readListBegin();
                struct.intValues = new ArrayList<Integer>(_list105.size);
                int _elem106;
                for (int _i107 = 0; _i107 < _list105.size; ++_i107)
                {
                  _elem106 = iprot.readI32();
                  struct.intValues.add(_elem106);
                }
                iprot.readListEnd();
              }
              struct.setIntValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LONG_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list108 = iprot.readListBegin();
                struct.longValues = new ArrayList<Long>(_list108.size);
                long _elem109;
                for (int _i110 = 0; _i110 < _list108.size; ++_i110)
                {
                  _elem109 = iprot.readI64();
                  struct.longValues.add(_elem109);
                }
                iprot.readListEnd();
              }
              struct.setLongValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // DOUBLE_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list111 = iprot.readListBegin();
                struct.doubleValues = new ArrayList<Double>(_list111.size);
                double _elem112;
                for (int _i113 = 0; _i113 < _list111.size; ++_i113)
                {
                  _elem112 = iprot.readDouble();
                  struct.doubleValues.add(_elem112);
                }
                iprot.readListEnd();
              }
              struct.setDoubleValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // DOC_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list114 = iprot.readListBegin();
                struct.docValues = new ArrayList<TDocument>(_list114.size);
                TDocument _elem115;
                for (int _i116 = 0; _i116 < _list114.size; ++_i116)
                {
                  _elem115 = new TDocument();
                  _elem115.read(iprot);
                  struct.docValues.add(_elem115);
                }
                iprot.readListEnd();
              }
              struct.setDocValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // PROPMAP_VALUES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list117 = iprot.readListBegin();
                struct.propmapValues = new ArrayList<TPropertyMap>(_list117.size);
                TPropertyMap _elem118;
                for (int _i119 = 0; _i119 < _list117.size; ++_i119)
                {
                  _elem118 = new TPropertyMap();
                  _elem118.read(iprot);
                  struct.propmapValues.add(_elem118);
                }
                iprot.readListEnd();
              }
              struct.setPropmapValuesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // LENGTH_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list120 = iprot.readListBegin();
                struct.lengthInfo = new ArrayList<Integer>(_list120.size);
                int _elem121;
                for (int _i122 = 0; _i122 < _list120.size; ++_i122)
                {
                  _elem121 = iprot.readI32();
                  struct.lengthInfo.add(_elem121);
                }
                iprot.readListEnd();
              }
              struct.setLengthInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TColumn struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.binaryValues != null) {
        oprot.writeFieldBegin(BINARY_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.binaryValues.size()));
          for (ByteBuffer _iter123 : struct.binaryValues)
          {
            oprot.writeBinary(_iter123);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.stringValues != null) {
        oprot.writeFieldBegin(STRING_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.stringValues.size()));
          for (String _iter124 : struct.stringValues)
          {
            oprot.writeString(_iter124);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.boolValues != null) {
        oprot.writeFieldBegin(BOOL_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.BOOL, struct.boolValues.size()));
          for (boolean _iter125 : struct.boolValues)
          {
            oprot.writeBool(_iter125);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.intValues != null) {
        oprot.writeFieldBegin(INT_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.intValues.size()));
          for (int _iter126 : struct.intValues)
          {
            oprot.writeI32(_iter126);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.longValues != null) {
        oprot.writeFieldBegin(LONG_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.longValues.size()));
          for (long _iter127 : struct.longValues)
          {
            oprot.writeI64(_iter127);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.doubleValues != null) {
        oprot.writeFieldBegin(DOUBLE_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.doubleValues.size()));
          for (double _iter128 : struct.doubleValues)
          {
            oprot.writeDouble(_iter128);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.docValues != null) {
        oprot.writeFieldBegin(DOC_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.docValues.size()));
          for (TDocument _iter129 : struct.docValues)
          {
            _iter129.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.propmapValues != null) {
        oprot.writeFieldBegin(PROPMAP_VALUES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.propmapValues.size()));
          for (TPropertyMap _iter130 : struct.propmapValues)
          {
            _iter130.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.lengthInfo != null) {
        oprot.writeFieldBegin(LENGTH_INFO_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.lengthInfo.size()));
          for (int _iter131 : struct.lengthInfo)
          {
            oprot.writeI32(_iter131);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TColumnTupleSchemeFactory implements SchemeFactory {
    public TColumnTupleScheme getScheme() {
      return new TColumnTupleScheme();
    }
  }

  private static class TColumnTupleScheme extends TupleScheme<TColumn> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TColumn struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBinaryValues()) {
        optionals.set(0);
      }
      if (struct.isSetStringValues()) {
        optionals.set(1);
      }
      if (struct.isSetBoolValues()) {
        optionals.set(2);
      }
      if (struct.isSetIntValues()) {
        optionals.set(3);
      }
      if (struct.isSetLongValues()) {
        optionals.set(4);
      }
      if (struct.isSetDoubleValues()) {
        optionals.set(5);
      }
      if (struct.isSetDocValues()) {
        optionals.set(6);
      }
      if (struct.isSetPropmapValues()) {
        optionals.set(7);
      }
      if (struct.isSetLengthInfo()) {
        optionals.set(8);
      }
      oprot.writeBitSet(optionals, 9);
      if (struct.isSetBinaryValues()) {
        {
          oprot.writeI32(struct.binaryValues.size());
          for (ByteBuffer _iter132 : struct.binaryValues)
          {
            oprot.writeBinary(_iter132);
          }
        }
      }
      if (struct.isSetStringValues()) {
        {
          oprot.writeI32(struct.stringValues.size());
          for (String _iter133 : struct.stringValues)
          {
            oprot.writeString(_iter133);
          }
        }
      }
      if (struct.isSetBoolValues()) {
        {
          oprot.writeI32(struct.boolValues.size());
          for (boolean _iter134 : struct.boolValues)
          {
            oprot.writeBool(_iter134);
          }
        }
      }
      if (struct.isSetIntValues()) {
        {
          oprot.writeI32(struct.intValues.size());
          for (int _iter135 : struct.intValues)
          {
            oprot.writeI32(_iter135);
          }
        }
      }
      if (struct.isSetLongValues()) {
        {
          oprot.writeI32(struct.longValues.size());
          for (long _iter136 : struct.longValues)
          {
            oprot.writeI64(_iter136);
          }
        }
      }
      if (struct.isSetDoubleValues()) {
        {
          oprot.writeI32(struct.doubleValues.size());
          for (double _iter137 : struct.doubleValues)
          {
            oprot.writeDouble(_iter137);
          }
        }
      }
      if (struct.isSetDocValues()) {
        {
          oprot.writeI32(struct.docValues.size());
          for (TDocument _iter138 : struct.docValues)
          {
            _iter138.write(oprot);
          }
        }
      }
      if (struct.isSetPropmapValues()) {
        {
          oprot.writeI32(struct.propmapValues.size());
          for (TPropertyMap _iter139 : struct.propmapValues)
          {
            _iter139.write(oprot);
          }
        }
      }
      if (struct.isSetLengthInfo()) {
        {
          oprot.writeI32(struct.lengthInfo.size());
          for (int _iter140 : struct.lengthInfo)
          {
            oprot.writeI32(_iter140);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TColumn struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(9);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list141 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.binaryValues = new ArrayList<ByteBuffer>(_list141.size);
          ByteBuffer _elem142;
          for (int _i143 = 0; _i143 < _list141.size; ++_i143)
          {
            _elem142 = iprot.readBinary();
            struct.binaryValues.add(_elem142);
          }
        }
        struct.setBinaryValuesIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list144 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.stringValues = new ArrayList<String>(_list144.size);
          String _elem145;
          for (int _i146 = 0; _i146 < _list144.size; ++_i146)
          {
            _elem145 = iprot.readString();
            struct.stringValues.add(_elem145);
          }
        }
        struct.setStringValuesIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list147 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.BOOL, iprot.readI32());
          struct.boolValues = new ArrayList<Boolean>(_list147.size);
          boolean _elem148;
          for (int _i149 = 0; _i149 < _list147.size; ++_i149)
          {
            _elem148 = iprot.readBool();
            struct.boolValues.add(_elem148);
          }
        }
        struct.setBoolValuesIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list150 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.intValues = new ArrayList<Integer>(_list150.size);
          int _elem151;
          for (int _i152 = 0; _i152 < _list150.size; ++_i152)
          {
            _elem151 = iprot.readI32();
            struct.intValues.add(_elem151);
          }
        }
        struct.setIntValuesIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list153 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.longValues = new ArrayList<Long>(_list153.size);
          long _elem154;
          for (int _i155 = 0; _i155 < _list153.size; ++_i155)
          {
            _elem154 = iprot.readI64();
            struct.longValues.add(_elem154);
          }
        }
        struct.setLongValuesIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list156 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.doubleValues = new ArrayList<Double>(_list156.size);
          double _elem157;
          for (int _i158 = 0; _i158 < _list156.size; ++_i158)
          {
            _elem157 = iprot.readDouble();
            struct.doubleValues.add(_elem157);
          }
        }
        struct.setDoubleValuesIsSet(true);
      }
      if (incoming.get(6)) {
        {
          org.apache.thrift.protocol.TList _list159 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.docValues = new ArrayList<TDocument>(_list159.size);
          TDocument _elem160;
          for (int _i161 = 0; _i161 < _list159.size; ++_i161)
          {
            _elem160 = new TDocument();
            _elem160.read(iprot);
            struct.docValues.add(_elem160);
          }
        }
        struct.setDocValuesIsSet(true);
      }
      if (incoming.get(7)) {
        {
          org.apache.thrift.protocol.TList _list162 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.propmapValues = new ArrayList<TPropertyMap>(_list162.size);
          TPropertyMap _elem163;
          for (int _i164 = 0; _i164 < _list162.size; ++_i164)
          {
            _elem163 = new TPropertyMap();
            _elem163.read(iprot);
            struct.propmapValues.add(_elem163);
          }
        }
        struct.setPropmapValuesIsSet(true);
      }
      if (incoming.get(8)) {
        {
          org.apache.thrift.protocol.TList _list165 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.lengthInfo = new ArrayList<Integer>(_list165.size);
          int _elem166;
          for (int _i167 = 0; _i167 < _list165.size; ++_i167)
          {
            _elem166 = iprot.readI32();
            struct.lengthInfo.add(_elem166);
          }
        }
        struct.setLengthInfoIsSet(true);
      }
    }
  }

}

