/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package se.lth.cs.docforia.io.thrift;


public enum TDataType implements org.apache.thrift.TEnum {
  D_NULL(0),
  D_BINARY(1),
  D_STRING(2),
  D_INT(3),
  D_LONG(4),
  D_FLOAT(5),
  D_DOUBLE(6),
  D_BOOLEAN(7),
  D_STRING_ARRAY(8),
  D_INT_ARRAY(9),
  D_LONG_ARRAY(10),
  D_FLOAT_ARRAY(11),
  D_DOUBLE_ARRAY(12),
  D_BOOLEAN_ARARY(13),
  D_PROPERTY_MAP(14),
  D_DOCUMENT(15),
  D_DOCUMENT_ARRAY(16);

  private final int value;

  private TDataType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TDataType findByValue(int value) { 
    switch (value) {
      case 0:
        return D_NULL;
      case 1:
        return D_BINARY;
      case 2:
        return D_STRING;
      case 3:
        return D_INT;
      case 4:
        return D_LONG;
      case 5:
        return D_FLOAT;
      case 6:
        return D_DOUBLE;
      case 7:
        return D_BOOLEAN;
      case 8:
        return D_STRING_ARRAY;
      case 9:
        return D_INT_ARRAY;
      case 10:
        return D_LONG_ARRAY;
      case 11:
        return D_FLOAT_ARRAY;
      case 12:
        return D_DOUBLE_ARRAY;
      case 13:
        return D_BOOLEAN_ARARY;
      case 14:
        return D_PROPERTY_MAP;
      case 15:
        return D_DOCUMENT;
      case 16:
        return D_DOCUMENT_ARRAY;
      default:
        return null;
    }
  }
}
