/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package se.lth.cs.docforia.io.thrift;


public enum TEdgeTypes implements org.apache.thrift.TEnum {
  RELATIONSHIP(0),
  DEPENDENCY_REL(1),
  SEMANTIC_ROLE(2),
  AST_EDGE(3),
  PARSE_TREE_EDGE(4);

  private final int value;

  private TEdgeTypes(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TEdgeTypes findByValue(int value) { 
    switch (value) {
      case 0:
        return RELATIONSHIP;
      case 1:
        return DEPENDENCY_REL;
      case 2:
        return SEMANTIC_ROLE;
      case 3:
        return AST_EDGE;
      case 4:
        return PARSE_TREE_EDGE;
      default:
        return null;
    }
  }
}
