/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package se.lth.cs.docforia.io.thrift;


public enum TSpecialKey implements org.apache.thrift.TEnum {
  NODE_RANGE_START_END(1),
  NODE_NUM_EDGE_OUT(2),
  EDGE_HEAD(3),
  DOC_ID(4),
  DOC_URI(5),
  DOC_LANG(6),
  DOC_TITLE(7),
  DOC_TEXT(8),
  DOC_TYPE(9);

  private final int value;

  private TSpecialKey(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TSpecialKey findByValue(int value) { 
    switch (value) {
      case 1:
        return NODE_RANGE_START_END;
      case 2:
        return NODE_NUM_EDGE_OUT;
      case 3:
        return EDGE_HEAD;
      case 4:
        return DOC_ID;
      case 5:
        return DOC_URI;
      case 6:
        return DOC_LANG;
      case 7:
        return DOC_TITLE;
      case 8:
        return DOC_TEXT;
      case 9:
        return DOC_TYPE;
      default:
        return null;
    }
  }
}
